### ISSUE TITLE
Add planning document to website

### ISSUE THREAD

**Issue by joakimmoller** [Odin-SMR/odin-api#72]
On the final meeting ESA asked us to publish the planning document (excel-file) together with some comments on how to interpret it.

@donal-mur can you send us the planning document?

Also add PVER-document

**Comment by donal-mur** [comment]
Latest version sent by e-mail

For most users the observing plan tab Is the most interesting. Here the date in in column B and the observing mode and description in columns R and S.
To understand the rest of the table we need to point out a few things about how the planing works. The orbit is divided into three sections north polar area, equitorial and south polar areas. Pointing and instrument modes can be set independently in each area.  Pointing modes can include the altitude range (stratmode 7-70 km, stratmesomode 1-120 km) and wether we point in the plane of the orbit or otherwise.   When non-standard modes are used the is a comment to point this out.
