### ISSUE TITLE
Publish warning for FM1 LO instability

### ISSUE THREAD

**Issue by joakimmoller** [Odin-SMR/odin-api#73]
ESA requested a warning on the webpage for a instrumental issue for years 2010-2017 with impact on FM1 data.

@donal-mur write a short note on what what message you want to publish as a comment in this issue.

**Comment by donal-mur** [comment]
Users are warned that data  from  FM01 may be unreliable between early 2010 and Jan 2018 due to a misbehaving local oscillator in the instrument. This has manifested itself by introducing asymmetric and broadened line shapes resulting in too low ozone and ClO values. We are looking at ways to mitigate the effect but until then please use FM01 data with caution.
