### ISSUE TITLE
API scans endpoint -

### ISSUE THREAD

**Issue by donal-mur** [Odin-SMR/odin-api#78]
API scans endpoint returns scan number and date and various URLS. Many scans will have the same date. ~This should be datetime instead~

For backwards compatibility reasons, we suggest adding time as a new attribute to
http://odin.rss.chalmers.se/apidocs/index.html#!/level2/get_rest_api_v5_level2_project_freqmode_scans

**Comment by skymandr** [comment]
Where is this used? Could this have consequences for processing?

**Comment by skymandr** [comment]
@donal-mur There are two scans endpoints, one for L1 and one for L2 [0]. Which one to you mean?

[0]: http://odin.rss.chalmers.se/apidocs/index.html

**Comment by donal-mur** [comment]
I was using the level 2 one-  while getting diagnostic info I send plot of -  I first found all the scans in a time period and then randomly selected a resonable number. the L2i data does not include the date and time and the scan endpoint only gave the time.  Seems like a lot of overhead to read the full L2 data just to get the date and time.

**Comment by donal-mur** [comment]
I don't think it affects the processing

**Comment by BengtRydberg** [comment]
Is it acceptable if we add the parameter TimeStart, so that the response look like this 

 {
      "Date": "string",
      "TimeStart": "string",
      "ScanID": 0,
      "URLS": {
        "URL-ancillary": "string",
        "URL-level2": "string",
        "URL-log": "string",
        "URL-spectra": "string"
      }
    }
and that the TimeStart represents the start time of the scan?

I guess that you ideally wants to have a time that is based on the MJD parameter
(mean time) as provided by
get /rest_api/v5/level2/{project}/{freqmode}/{scanno}/L2/ 
but if we implement this the query will be much slower, because
then we need to scan trough a much bigger database table in order to fetch the data.
